#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/database
- name: Run Database Container
  docker_container:
    name: database
    image: charlotterib/tp-devops-database:latest
    networks:
      - name: app-network
    env:
      # Reprends exactement les mêmes variables et valeurs que ton docker-compose
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - db-data:/var/lib/postgresql/data # 💾 Permet de ne pas perdre tes données si le conteneur redémarre
    restart_policy: always