#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/app
- name: Run Backend App
  docker_container:
    name: simple-api
    image: charlotterib/tp-devops-simple-api:latest
    networks:
      - name: app-network
    env:
      # Ajuste le nom de la variable selon ce que demande ton code Java/Spring
      # Note l'utilisation du nom du conteneur "database" dans l'URL
      SPRING_DATASOURCE_URL: "{{SPRING_DATASOURCE_URL}}"
      SPRING_DATASOURCE_USERNAME: "{{SPRING_DATASOURCE_USERNAME}}"
      SPRING_DATASOURCE_PASSWORD: "{{SPRING_DATASOURCE_PASSWORD}}"
    restart_policy: always