#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/proxy
- name: Run HTTPD Proxy
  docker_container:
    name: httpd
    image: charlotterib/tp-devops-httpd:latest
    ports:
      - "80:80" # 🌍 Ouvre l'accès depuis ton navigateur
    networks:
      - name: app-network
    restart_policy: always