name: CD devops 2025

on:
  workflow_run: 
    workflows: ["CI devops 2025"]
    branches: [main]
    types:
      - completed

jobs:
  build-database:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: DevOps_TP1/tp-devops-correction-docker/database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          no-cache: true

  build-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: DevOps_TP1/tp-devops-correction-docker/simple-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          no-cache: true
    
  build-httpd:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          # 🌟 On s'arrête au dossier parent pour le contexte
          context: DevOps_TP1/tp-devops-correction-docker
          # 📄 On lui indique explicitement où trouver le Dockerfile maintenant
          file: DevOps_TP1/tp-devops-correction-docker/http-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          no-cache: true

  deploy:
    needs: [build-database, build-backend, build-httpd]
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # 🔍 Étape temporaire ajoutée pour espionner les dossiers de GitHub
      - name: List files to find playbook
        run: |
          echo "--- OÙ SUIS-JE ? ---"
          pwd
          echo "--- LISTE DES DOSSIERS ---"
          ls -R

      # 🎬 Ton étape Ansible (qui va peut-être couper, mais c'est normal pour le test)
      - name: Run Ansible Playbook
        run: ansible-playbook -i DevOps_TP1/ansible/inventories/setup.yml DevOps_TP1/ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
        