name: CI devops 2025
on:
push:
branches:
  - main
  - develop
pull_request:
jobs:
test-backend:
runs-on: ubuntu-24.04
steps:
  - uses: actions/checkout@v4
  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '21'

    # Une seule étape de build claire, nette et précise
  - name: Build, test and analyze with SonarCloud
    run: mvn -B verify sonar:sonar -Dsonar.projectKey=Charlotterib_DevOps -Dsonar.organization=charlotterib -Dsonar.host.url=[https://sonarcloud.io](https://sonarcloud.io) -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file DevOps_TP1/tp-devops-correction-docker/simple-api/pom.xml
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

build-and-push-docker-image:
needs: test-backend
runs-on: ubuntu-24.04
steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: DevOps_TP1/tp-devops-correction-docker/simple-api
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        context: DevOps_TP1/tp-devops-correction-docker/database
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        context: DevOps_TP1/tp-devops-correction-docker/http-server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
