name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:  [main,develop]
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
      #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file DevOps_TP1/tp-devops-correction-docker/simple-api/pom.xml

  sonar-analysis:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Run SonarCloud Analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Charlotterib_DevOps -Dsonar.organization=charlotterib -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file DevOps_TP1/tp-devops-correction-docker/simple-api/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # steps to perform in job
  build-database:
    needs: sonar-analysis
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: DevOps_TP1/tp-devops-correction-docker/simple-api
          push: ${{ github.ref == 'refs/heads/main' }} 
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

  build-backend:
    needs: build-database
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: DevOps_TP1/tp-devops-correction-docker/simple-api
          push: ${{ github.ref == 'refs/heads/main' }} 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
    
  build-httpd:
    needs: build-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: DevOps_TP1/tp-devops-correction-docker/http-server
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
