name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:  [main,develop]
  pull_request:
  workflow_call:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
      #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file DevOps_TP1/tp-devops-correction-docker/simple-api/pom.xml

  sonar-analysis:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Run SonarCloud Analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Charlotterib_DevOps -Dsonar.organization=charlotterib -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file DevOps_TP1/tp-devops-correction-docker/simple-api/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

deploy:
    needs: [build-and-push-docker-images] # Attend que les images soient bien sur le Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false' #  Évite que GitHub bloque en demandant "Voulez-vous faire confiance à ce serveur ?"